name: Reusable workflow to execute WPT against Servo nightly.

env:
  NIGHTLY_PATH: https://download.servo.org/nightly/linux/servo-latest.tar.gz

on:
  workflow_call:
    inputs:
      layout-engine:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  run-wpt:
    name: Run WPT suite. 
    runs-on: ubuntu-22.04
    env:
      max_chunk_id: 20
    strategy:
      matrix:
        chunk_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Checkout servo repo
        uses: actions/checkout@v3
        with:
          repository: servo/servo
          path: servo
      - name: Prep test environment
        run: |
          python3 -m pip install --upgrade pip virtualenv
          sudo apt update
          sudo apt install -qy --no-install-recommends mesa-vulkan-drivers
      - name: Download latest nightly
        run: |
          ./mach bootstrap
          wget -O servo-latest.tar.gz "${{ env.NIGHTLY_PATH }}"
          tar -xzf servo-latest.tar.gz
          mkdir -p target/release
          mv servo/resources target/release/resources
          mv servo/servo target/release/servo

          SERVO_VERSION=$(./target/release/servo --version)
          echo Downloaded $SERVO_VERSION
          echo "SERVO_VERSION=$SERVO_VERSION" >> $GITHUB_ENV
        working-directory: servo
      - name: Run tests
        run: |
          python3 ./mach test-wpt \
            --release ${WPT_LAYOUT_FLAG} \
            --log-wptreport=wpt-report-${{ matrix.chunk_id }}.json \
            --processes $(nproc) --timeout-multiplier 2 \
            --always-succeed \
            --browser-version "$SERVO_VERSION" \
            --this-chunk ${{ matrix.chunk_id }} \
            --total-chunks ${{ env.max_chunk_id }}
        working-directory: servo
      - name: Archive the wpt result chunk
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }} 
          path: servo/wpt-report-${{ matrix.chunk_id }}.json

